spring.application.name=ridego

jwt.secret=${JWT_SECRET}
jwt.expirationMs=86400000

server.port=${PORT:9091}

ors.api-key=${ORS_API_KEY:}
gemini.api-key=${GEMINI_API_KEY:}
gemini.model=${GEMINI_MODEL:gemini-2.5-flash}

spring.data.mongodb.database=ridego
spring.data.mongodb.uri=${MONGODB_URI}

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

razorpay.key-id=${RAZORPAY_KEY_ID:}
razorpay.key-secret=${RAZORPAY_KEY_SECRET:}
razorpay.webhook-secret=${RAZORPAY_WEBHOOK_SECRET:}
